val article = "{\"id\": \"53e99784b7602d9701f3e4f2\", \"title\": \"Hypoxia may increase rat insulin mRNA levels by promoting binding of the polypyrimidine tract-binding protein (PTB) to the pyrimidine-rich insulin mRNA 3'-untranslated region.\", \"authors\": [{\"name\": \"Linda Tillmar\"}, {\"name\": \"Nils Welsh\"}], \"venue\": \"Molecular medicine (Cambridge, Mass.)\", \"year\": 2002, \"keywords\": [\"wild type\", \"insulin\", \"hydrogen peroxide\", \"oxygen\", \"nitric oxide\", \"tyrosine hydroxylase\", \"untranslated region\", \"reporter gene\", \"partial pressure\", \"electrophoretic mobility shift assay\"], \"n_citation\": 8, \"page_start\": \"263\", \"page_end\": \"272\", \"lang\": \"en\", \"volume\": \"8\", \"issue\": \"5\", \"issn\": \"1076-1551\", \"url\": [\"http://www.ncbi.nlm.nih.gov/pubmed/12359957?report=xml&format=text\"], \"abstract\": \"Recent reports identify the 3'-UTR of insulin mRNA as crucial for control of insulin messenger stability. This region contains a pyrimidine-rich sequence, which is similar to the hypoxia-responsive mRNA-stabilizing element of tyrosine hydroxylase. This study aimed to determine whether hypoxia affects insulin mRNA levels.Rat islets were incubated at normoxic or hypoxic conditions and with or without hydrogen peroxide and a nitric oxide donor. Insulin mRNA was determined by Northern hybridization. Islet homogenates were used for electrophoretic mobility shift assay with an RNA-oligonucleotide, corresponding to the pyrimidine-rich sequence of the 3'-UTR of rat insulin I mRNA. The expression of reporter gene mRNA, in islets transfected with reporter gene constructs containing the wild-type or mutated insulin mRNA pyrimidine-rich sequences, was measured by semiquantitive RT-PCR.Insulin mRNA was increased in response to hypoxia. This was paralleled by increased binding of the polypyrimidine tract-binding protein (PTB) to the pyrimidine-rich sequence of the 3'-UTR of insulin mRNA, which was counteracted by hydrogen peroxide. The reporter gene mRNA level containing the wild-type binding site was not increased in response to hypoxia, but mutation of the site resulted in a destabilization of the mRNA.The complete understanding of different diabetic conditions requires the elucidation of mechanisms that control insulin gene expression. Our data show that hypoxia may increase insulin mRNA levels by promoting the binding of PTB to the insulin mRNA 3'-UTR. Hydrogen peroxide abolishes the hypoxic effect indicating involvement of reactive oxygen species and/or the redox potential in the oxygen-signaling pathway.\", \"references\": [\"53e9a611b7602d9702f42159\", \"53e9b316b7602d9703ddd6aa\", \"53e9a689b7602d9702fbc829\", \"53e9bc21b7602d970488e3be\", \"53e9b7a5b7602d970434e2a8\", \"53e9a718b7602d970304d0cd\", \"53e9b4a0b7602d9703fa9916\", \"53e9a38fb7602d9702c9ed97\", \"53e9a298b7602d9702b9e65f\"]}"

def parse(line: String): (String, String) = {
  val separator = "\"abstract\": \""
  val i = line.indexOf(separator)
  val j = line.indexOf("\"", i + separator.length)
  val id = line.substring(8, 32)
  val abstr  = line.substring(i + separator.length, j)
  (id, abstr)
}

val derp = parse(article)